# Compose file for launching the test setup with
# a Peer for fitcp 
# RAFT

version: '2'

networks:
  fitcp:

# Storage for additional orderer containers
volumes:
  data-orderer.fitcp.com:



services:
  # orderer service
  orderer.fitcp.com:
    container_name: orderer.fitcp.com
    image: hyperledger/fabric-orderer
    command: orderer
    # Override environment variables for orderer in this section
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=INFO
      # TLS Setup
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/tls/ca.crt]
      # RAFT related setup
      
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/tls/ca.crt]
    # Host folder mappings
    volumes:
    # Folder with genesis block
      - ${PWD}/config/orderer:/var/hyperledger/config
    # Map the folder with MSP for orderer
      - ${PWD}/config/crypto-config/ordererOrganizations/fitcp.com/orderers/orderer.fitcp.com/msp:/var/hyperledger/msp
    # Added to support the TLS setup
      - ${PWD}/config/crypto-config/ordererOrganizations/fitcp.com/orderers/orderer.fitcp.com/tls:/var/hyperledger/tls
      - data-orderer.fitcp.com:/var/ledger
    ports:
      - 7050:7050
    networks:
      - fitcp


